### ISSUE TITLE
SWI-Prolog 9.1.19 FLI updates

### ISSUE THREAD

**Issue by morlic** [terminusdb-labs/swipl-rs#54]
Hi,
it seems that swipl 9.1.19 broke the interface definitions as the `swipl-rs` code fails to compile against it.
Works fine on 9.1.18 this note in the changelog looks like the culprit:

```
[Nov 1 2023]

CLEANUP: PL_new_term_refs() now takes size_t argument (was int).
```

[diff 9.1.18->9.1.22](https://www.swi-prolog.org/ChangeLog?branch=development&from=9.1.18&to=9.1.22)

```log
   Compiling swipl v0.3.15
error[E0308]: mismatched types
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swipl-0.3.15/src/callable.rs:307:42
    |
307 |             let terms = PL_new_term_refs(N as i32);
    |                         ---------------- ^^^^^^^^ expected `usize`, found `i32`
    |                         |
    |                         arguments to this function are incorrect
    |
note: function defined here
   --> /builds/cognitive-layer/main/otel-swipl/rust/target/release/build/swipl-fli-16c36fc58db1b938/out/bindings.rs:3:166569
    |
3   | ...extern "C" { # [doc = "        TERM-REFERENCES\t*"] pub fn PL_new_term_refs (n : usize) -> term_t ; } extern "C" { pub fn PL_new_term_...
    |                                                               ^^^^^^^^^^^^^^^^
help: you can convert an `i32` to a `usize` and panic if the converted value doesn't fit
    |
307 |             let terms = PL_new_term_refs((N as i32).try_into().unwrap());
    |                                          +        +++++++++++++++++++++
error[E0308]: mismatched types
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swipl-0.3.15/src/context.rs:633:54
    |
633 |         let mut term_ptr = unsafe { PL_new_term_refs(N as i32) };
    |                                     ---------------- ^^^^^^^^ expected `usize`, found `i32`
    |                                     |
    |                                     arguments to this function are incorrect
    |
note: function defined here
   --> /builds/cognitive-layer/main/otel-swipl/rust/target/release/build/swipl-fli-16c36fc58db1b938/out/bindings.rs:3:166569
    |
3   | ...extern "C" { # [doc = "        TERM-REFERENCES\t*"] pub fn PL_new_term_refs (n : usize) -> term_t ; } extern "C" { pub fn PL_new_term_...
    |                                                               ^^^^^^^^^^^^^^^^
help: you can convert an `i32` to a `usize` and panic if the converted value doesn't fit
    |
633 |         let mut term_ptr = unsafe { PL_new_term_refs((N as i32).try_into().unwrap()) };
    |                                                      +        +++++++++++++++++++++
error[E0308]: mismatched types
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swipl-0.3.15/src/context.rs:662:54
    |
662 |         let mut term_ptr = unsafe { PL_new_term_refs(count as i32) };
    |                                     ---------------- ^^^^^^^^^^^^ expected `usize`, found `i32`
    |                                     |
    |                                     arguments to this function are incorrect
    |
note: function defined here
   --> /builds/cognitive-layer/main/otel-swipl/rust/target/release/build/swipl-fli-16c36fc58db1b938/out/bindings.rs:3:166569
    |
3   | ...extern "C" { # [doc = "        TERM-REFERENCES\t*"] pub fn PL_new_term_refs (n : usize) -> term_t ; } extern "C" { pub fn PL_new_term_...
    |                                                               ^^^^^^^^^^^^^^^^
help: you can convert an `i32` to a `usize` and panic if the converted value doesn't fit
    |
662 |         let mut term_ptr = unsafe { PL_new_term_refs((count as i32).try_into().unwrap()) };
    |                                                      +            +++++++++++++++++++++
error[E0308]: mismatched types
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swipl-0.3.15/src/dict.rs:210:58
    |
210 |         let value_terms = unsafe { fli::PL_new_term_refs(len as i32) };
    |                                    --------------------- ^^^^^^^^^^ expected `usize`, found `i32`
    |                                    |
    |                                    arguments to this function are incorrect
    |
note: function defined here
   --> /builds/cognitive-layer/main/otel-swipl/rust/target/release/build/swipl-fli-16c36fc58db1b938/out/bindings.rs:3:166569
    |
3   | ...extern "C" { # [doc = "        TERM-REFERENCES\t*"] pub fn PL_new_term_refs (n : usize) -> term_t ; } extern "C" { pub fn PL_new_term_...
    |                                                               ^^^^^^^^^^^^^^^^
help: you can convert an `i32` to a `usize` and panic if the converted value doesn't fit
    |
210 |         let value_terms = unsafe { fli::PL_new_term_refs((len as i32).try_into().unwrap()) };
    |                                                          +          +++++++++++++++++++++
For more information about this error, try `rustc --explain E0308`.
error: could not compile `swipl` (lib) due to 4 previous errors

```

**Comment by morlic** [comment]
https://github.com/SWI-Prolog/swipl-devel/commit/0a8722a2b0f965ad19e30f4335979019b1a3e5c3 is the commit in swipl repo

**Comment by morlic** [comment]
duplicate of #53 , closing
